tests: add cpuset hierarchy test
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@futurfusion.io>

diff --git a/tests/lib.sh.in b/tests/lib.sh.in
--- a/tests/lib.sh.in
+++ b/tests/lib.sh.in
@@ -2,14 +2,16 @@
 # SPDX-License-Identifier: LGPL-2.1+
 
 check_requirements() {
-	[ "$(id -u)" -eq 0 ] || { echo "Error: test should be run as root" >&2; exit 1; }
+	if [ -z "${LXCFS_TEST_IN_CT:-}" ]; then
+		[ "$(id -u)" -eq 0 ] || { echo "Error: test should be run as root" >&2; exit 1; }
 
-	# a naive but simple check if we are inside user namespace
-	[ "$(readlink /proc/1/ns/user)" = "$(readlink /proc/self/ns/user)" ] || { echo "Error: test should be run in init_user_ns" >&2; exit 1; }
+		# a naive but simple check if we are inside user namespace
+		[ "$(readlink /proc/1/ns/user)" = "$(readlink /proc/self/ns/user)" ] || { echo "Error: test should be run in init_user_ns" >&2; exit 1; }
 
-	grep -F 'cgroup2 cgroup2' /proc/1/mountinfo | grep -qF ' /sys/fs/cgroup ' || { echo "Error: cgroup2 is expected" >&2; exit 1; }
+		grep -F 'cgroup2 cgroup2' /proc/1/mountinfo | grep -qF ' /sys/fs/cgroup ' || { echo "Error: cgroup2 is expected" >&2; exit 1; }
 
-	[ -d /sys/fs/cgroup ] || { echo "Error: cgroupfs must be accessible at /sys/fs/cgroup" >&2; exit 1; }
+		[ -d /sys/fs/cgroup ] || { echo "Error: cgroupfs must be accessible at /sys/fs/cgroup" >&2; exit 1; }
+	fi
 }
 
 init_cgroups() {
diff --git a/tests/test_meminfo_hierarchy.sh.in b/tests/test_meminfo_hierarchy.sh.in
--- a/tests/test_meminfo_hierarchy.sh.in
+++ b/tests/test_meminfo_hierarchy.sh.in
@@ -8,9 +8,11 @@ set -eu
 
 check_requirements
 
-# Test requires at least 256 MiB of swap to function
-system_swap_size=$(awk '/^SwapTotal:/ { print $2 }' /proc/meminfo)
-[ "$system_swap_size" -ge "$((256 * 1024))" ] || { echo "Error: swap < 256 MiB" >&2; exit 1; }
+if [ -z "${LXCFS_TEST_IN_CT:-}" ]; then
+	# Test requires at least 256 MiB of swap to function
+	system_swap_size=$(awk '/^SwapTotal:/ { print $2 }' /proc/meminfo)
+	[ "$system_swap_size" -ge "$((256 * 1024))" ] || { echo "Error: swap < 256 MiB" >&2; exit 1; }
+fi
 
 LXCFSDIR=${LXCFSDIR:-/var/lib/lxcfs}
 
