github: Validate target branch
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -22,3 +22,19 @@ jobs:
       uses: tim-actions/dco@master
       with:
         commits: ${{ steps.get-pr-commits.outputs.commits }}
+
+  target-branch:
+    permissions:
+      contents: none
+    name: Branch target
+    runs-on: ubuntu-20.04
+    steps:
+    - name: Check branch target
+      env:
+        TARGET: ${{ github.event.pull_request.base.ref }}
+      run: |
+        set -x
+        [ "${TARGET}" = "master" ] && exit 0
+
+        echo "Invalid branch target: ${TARGET}"
+        exit 1
